### ISSUE TITLE
Add required fields for projects tab

### ISSUE THREAD

**Issue by Ben-Wu** [HumanCellAtlas/metadata-api#20]
Figure out which fields are needed for projects tab and add them.

At least `project_title` and `contributors` are required.

**Comment by Ben-Wu** [comment]
WIP branch: https://github.com/Ben-Wu/metadata-api/tree/feature/benwu/projects-tab

**Comment by malloryfreeberg** [comment]
As per the metadata standard, the following fields are required:
`project_short_name`
`project_title`
`project_description`
