### ISSUE TITLE
Use ontology terms where applicable

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-api#31]
Library construction approach is currently extracted from the [library_construction_approach.text](https://github.com/HumanCellAtlas/metadata-schema/blob/80e064837c5a9db713618a2cf6bcf6661ad8247e/examples/bundles/public-beta/1M%20Immune%20Cells/library_preparation_protocol_0.json#L18) field. This is a user-supplied, unrestricted text field that could take various values, all representing the same approach (`“smart-seq2” or “Smart-seq2" or “SS2” `).

Consider using the sibling field `ontology` instead.

To avoid displaying the ontology term ID in the browser, at some point it should be mapped back to a human-readable form, potentially using the ontological term label.

http://ontology.staging.data.humancellatlas.org/ontologies/efo/terms?iri=http%3A%2F%2Fwww.ebi.ac.uk%2Fefo%2FEFO_0008931`

**Comment by hannes-ucsc** [comment]
@simonjupp, you mentioned on Slack that the ontology term label is also in the metadata. I can't find it in the pilot examples. It also is not a required field either. Then again, neither are `text` or `ontology`. What's the semantics here? Shouldn't all three be required?

**Comment by simonjupp** [comment]
It's not required as mapping data to ontology terms usually happens after submission. Our role in this project is in part to make sure there are ontology terms for everything and we're building tools to help the users/wranglers with this. 

You can get the label using our ontology service API http://ontology.staging.data.humancellatlas.org/api/terms?id=EFO:0008931. We'll most likely inject this into the metadata in the future when an ontology term is validated. You can also use the API to get you all the parents/related terms and synonyms that can be used to support things like query expansion and autocomplete. e.g. a search on "nervous system" should return data about parts of the nervous system http://ontology.staging.data.humancellatlas.org/ontologies/hcao/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001016. 

Let's set some time aside to discuss strategies for indexing, searching and faceting with ontologies at the next face to face. cc @daniwelter

**Comment by hannes-ucsc** [comment]
Happy to discuss this further. I would like to register some concern, though. Submitting metadata with field values that could or could not have a matching ontology term is easy for the producer but hard for the consumer of the metadata. This seems to be a recurring scheme in our exchanges. I thought the point of ontologies was to simplify the consumption of data. The process of injecting ontology terms later means that I as a consumer have to handle more cases in my code. It would make my life more complicated, not simpler.

Pinging @theathorn to see if we can reserve some time for a meeting at the F2F.

**Comment by diekhans** [comment]
Count me in on the concern.  It seems like an opportunity for error and loss of knowledge to be translating submitter entires to ontologies downstream.

**Comment by simonjupp** [comment]
This is all valid, we just have to be clear on where we put that cost. If we ask that all data being submitted must be annotated with ontology terms, then this will make preparing and submitting data to HCA harder for the user, but we should get higher quality data coming through the system. There will be cases where new data types will come along for which we don't yet have an ontology term, so submissions can either be held up while new terms are created or the data can be ingested but it would have missing information so may not show up in the browser or trigger workflows etc. 

I'm happy to review which ontology fields should be made required. In this instance I'd support making a request to the metadata team that the ontology id is also be required for `library construction` as this is fundamental for triggering workflows and driving facets on the data portal. 
http://schema.dev.data.humancellatlas.org/module/ontology/1.2.2/library_construction_ontology

**Comment by hannes-ucsc** [comment]
A few things to consider: if a `.ontology` field is required, the `.text` sibling shouldn't even be specified in the schema. If an `.ontology` field is optional, the `.text` sibling should only be allowed to be present in the document if the corresponding `.ontology` field is absent.

Re cost: Isn't the cost on the submitter actually less if ontology terms are mandatory? If there is intent to specify an ontology term at some later point in time, the metadata will have to be submitted twice. If the term is mandatory, it is only submitted once. The cost on the consumer is higher in the "optional" case because of increased complexity in consuming the data and the potential necessity to analyze the affected bundles twice.

**Comment by simonjupp** [comment]
I think you always want to give the user the option to add some free text in cases where the ontology term isn't a 1-1 mapping. 

Consider if we made `organism_part.ontology` required and someone wants to tell us the sample was `Fetal skeletal muscle`. There is no single ontology term for this as it combines an anatomy term and a developmental stage. If we mandate an ontology term the submitter may simply choose the less specific `skeletal muscle` from our ontology and then we've lost an important piece of data. In this case you want to allow the full expressivity of natural language to avoid any potential loss of information, and also then enrich that with ontology tags to give it some context and semantics that we can compute with. 

The more a submitter has to do to understand our schema and see that something like development stage has a specific slot is cost. By mandating ontologies and forcing the submitter to spend time searching through them to find a term that matches 1-1 with their intention adds more cost. Ask any of the wranglers, this is time consuming and has already required several additions to the HCA ontology before the initial datasets could be validated and submitted. 

Let's take this up with the metadata team starting with `Library construction approach` as I think this does have a strong case for having a mandatory ontology id and no need for a text field. The  consequences from this of course is that we wouldn't be able to ingest any new data that used a library construction approach not represented in our ontology (which may or may not be desirable depending on your point of view)

**Comment by hannes-ucsc** [comment]
> By mandating ontologies and forcing the submitter to spend time searching through them to find a term that matches 1-1 with their intention adds more cost.  Ask any of the wranglers, this is time consuming and has already required several additions to the HCA ontology before the initial datasets could be validated and submitted.

Isn't that the very definition of the job of a wrangler? It's what they do. If we only considered the effort on the wrangling side, why don't we make their job extremely easy by not requiring any metadata at all? Clearly not an option. This is a trade-off: Cost ingestion vs. cost of consumption.

In the `Fetal skeletal muscle` example, the submitter would be tempted to leave the `organism_part.ontology` empty. They don't find a match and simply cram it in the free-form text field. This would mean that consumers searching for the `Sceletal muscle` ontology term would not find those bundles with `organism_part.text` set to `Fetal skeletal muscle`.

Yes wrangling is hard, takes time and effort. Hence the name. If we don't wrangle the data on the production side, our users will forever be doomed to wrangle it on the consumption side. Considering that hopefully we will have orders of magnitude more consumption than production (otherwise the project will have failed), we should place the burden on the producer. Our approach should be to start with strict validation on ingest and relax only if absolutely necessary.

**Comment by hannes-ucsc** [comment]
Demoed on 3/1/2019
