### ISSUE TITLE
Fix test cases by using bundles from production

### ISSUE THREAD

**Issue by danielsotirhos** [HumanCellAtlas/metadata-api#46]
The following test cases currently fail because they are attempting to use bundles on staging that are no longer available. Fix these test cases by using equivalent bundles from production.

test/test.py
- test_vx_primary_cs_bundle()
- test_vx_analysis_cs_bundle()
- test_vx_analysis_specimen_bundle()

**Comment by hannes-ucsc** [comment]
Moved to https://github.com/DataBiosphere/hca-metadata-api/issues/7
