### ISSUE TITLE
Add test for canonical example metadata

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-api#57]
We can eliminate some of the coordination that's required to absorb schema changes in downstream components by having one exemplary set of metadata in the `metadata-schema` repository and a corresponding test case in this repository. Every PR in the `metadata-schema` repository would update the exemplary set of metadata and, when merged, trigger a build in the `metadata-api` repository. Ideally, the exemplary set of metadata would exercise every metadata entity and every property and maybe a few common graph shapes.  The test in the `metadata-api` repository would test the latest exemplary metadata from the `master` branch of the `metadata-schema` repository as well as select older commits, potentially those labelled with a release label. Testing older commits ensures backwards compatibility of the latest `metadata-api` release with previous schema releases.

@theathorn @NoopDog @malloryfreeberg

**Comment by malloryfreeberg** [comment]
@hannes-ucsc we could add some functionality to the metadata-schema repo that automatically generates some metadata JSON from the schema (we have some code that can generate a spreadsheet from the schema, and then we can use the ingest importer in a dry-run mode to generate JSON from the spreadsheet). However, JSON generated in this way it will look slightly different than what is stored in the Data Store (e.g. no provenance information, not in "bundle" structure). 

Would this be a reasonable first step? 

Curious where the plan is for metadata update testing @mweiden @diekhans et al. as I believe the plan covers some of this work.

**Comment by hannes-ucsc** [comment]
> Would this be a reasonable first step?

Yes. We could add this as part of your build process. When a change lands on a main branch of the metadata-schema repository, an additional build step could generate the example JSONs, feeds them to the metadata-api and compares the actual result to an expected result. Any difference would indicate that `metadata-api` would have to be updated. It would be up to you if you treated this as a hard failure or just a warning. It would eliminate the need to manually check if schema change breaks the API or not.

The generated JSON would have to be deterministic and exercise every entity and every property of every entity.

@malloryfreeberg

**Comment by hannes-ucsc** [comment]
#75 is a good example of an issue that we could avoid with testing metadata-api as part of the metadata-schema build.

**Comment by mweiden** [comment]
@malloryfreeberg @hannes-ucsc: Here's @maniarathi's [design draft](https://docs.google.com/document/d/18C_Wbrr4Huc8yxQXSdNbzeGk0glBjkfq0MGnozwlIB8/edit#bookmark=id.ry2cic8h68v5).

@malloryfreeberg You're right that there is some overlap: both approaches generate some test metadata for testing purposes. The difference is that this issue proposes testing specifically `metadata-api` while the integration test design tests the end-to-end function of DCP.

**Comment by maniarathi** [comment]
There are two tools already in place to describe some of the stuff that I'm seeing in this ticket:

1) Matt Greene developed a tool to generate spreadsheets (filled out and linked) based on a schema. Two additional pieces of work will need to be done to fill this out which I will be taking on: one is to add a process ID column so that bundles can contain more than one file (today the column is absent leading to the creating of one bundle per file) and two to do a post-generation fill to the spreadsheet with specific secondary analysis trigger values so that secondary analysis doesn't ignore all the outputted data from Ingest/DSS. This tool lives here: https://github.com/HumanCellAtlas/ingest-client/tree/mg-links_builderv2. Rodrick from Ingest (?), I think, has been tasked with merging the branch into master.

2) Trent Smith has developed a tool to generate metadata JSON files (i.e. the output of Ingest) based on the schema, bypassing the spreadsheet altogether. That tool lives here: https://github.com/HumanCellAtlas/dcp-pyjsongen.

I will be using Matt's tool for the schema system tests but it looks like Hannes, you might want Trent's tool. Let me know if you have any questions!

**Comment by hannes-ucsc** [comment]
@maniarathi, not sure I want dcp-pyjsongen. Last time I checked it produced rather sparse instances of the schema and was non-deterministic. I need deterministic and complete coverage of the schema.

**Comment by diekhans** [comment]
@hannes-ucsc, you are the customer.  What do **you** need to ensure adequate test coverage? What kind of invalid data as well a valid data?

**Comment by maniarathi** [comment]
Agreeing with Mark here. I think we can definitely built out the existing tool to accommodate your use cases, Hannes. This seems like a better option than building a whole new tool all over again. Let me know if you'd like to chat sometime about it and I can rope in Trent as well.

The plus side is that once we build it out, I think this would encourage others to create tests more easily as well!

**Comment by hannes-ucsc** [comment]
Though I'm not convinced that a random approach would work best for my use case, I'm sure that can be addressed by either extending existing tooling or developing new tooling. Thank you for offering to help with that, @maniarathi.

However, I think we got a little side-tracked, here. The big question I have for @malloryfreeberg is if the metadata team would accept a PR that excercised `metadata-api` tests as part of the `metadata-schema` CI build.

**Comment by diekhans** [comment]
>  The big question I have for @malloryfreeberg is if the metadata team would accept a PR that excercised `metadata-api` tests as part of the `metadata-schema` CI build.

I am supportive of this anything to detect problems early. Although it is not my decision.

**Comment by malloryfreeberg** [comment]
> the metadata team would accept a PR that exercised metadata-api tests as part of the metadata-schema CI build.

I think this sounds like an excellent idea. 

I will need to understand the downstream consequences a bit more, but as long as a failing metadata-api test doesn't block the (pre-)release of metadata schema changes to support ingesting raw data or analysis results, I'm on board.

**Comment by hannes-ucsc** [comment]
Moved to https://github.com/DataBiosphere/hca-metadata-api/issues/5
