### ISSUE TITLE
Add README.md to this repo

### ISSUE THREAD

**Issue by kozbo** [HumanCellAtlas/metadata-api#6]
# WHY
As a user of the metadata api I would expect a readme to tell me how to install and use this api

# DoD
 - [ ] How to install
 - [ ] How to test installation
 - [ ] pointer to example code

Here is some explanatory text I created elsewhere that might be of use here in the readme:
`Background: the metadata-api is meant to provide a programmatic abstraction layer between the metadata and its consumers in the data store and browser layers. It provides a library that has functions to call to retrieve the most common data types. This insulates the consumers from most changes that happen at the metadata layer. `

**Comment by theathorn** [comment]
Dup of #85.
