### ISSUE TITLE
Metadata is read from AWS replica, even if GCP is requested

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-api#65]
The bundle is read from the selected replica but the individual files are always read from `aws` because this line hard-codes the replica.

https://github.com/HumanCellAtlas/metadata-api/blob/07d6bcb5049b861f79f84160cccceb1f5ad00cf4/src/humancellatlas/data/metadata/helpers/dss.py#L79

This issue incidentally masks a bug in the DSS: https://github.com/HumanCellAtlas/data-store/issues/2073

**Comment by hannes-ucsc** [comment]
@rexwangcc, @samanehsan, if you're still using metadata-api, this may affect you.

**Comment by rexwangcc** [comment]
Yeah, I think it does affect us, thanks for tagging! @hannes-ucsc

**Comment by hannes-ucsc** [comment]
Demoed on 5/28/2019
