### ISSUE TITLE
Add support for `file_core.content description`

### ISSUE THREAD

**Issue by hannes-ucsc** [HumanCellAtlas/metadata-api#82]
https://github.com/HumanCellAtlas/metadata-schema/issues/542

https://github.com/HumanCellAtlas/metadata-schema/blob/8f507048115a7fb9e93545d3159df247bd7ee5b9/json_schema/core/file/file_core.json#L38

Note that field is ontologized.

**Comment by malloryfreeberg** [comment]
As always, the `.text` component will be required (the user-supplied free text string), and the `.ontology_label` component is optional but will contain the standardized text.

**Comment by hannes-ucsc** [comment]
Spike to see if at least some bundles in `prod` have this filled in. Otherwise post-pone.

**Comment by danielsotirhos** [comment]
Ran a post /search on prod swagger with
```
{"es_query": {"query": {"exists": {"field": "*.content_description.*"}}}}
```
and got zero results
```
{
  "es_query": {
    "query": {
      "exists": {
        "field": "*.content_description.*"
      }
    }
  },
  "results": [],
  "total_hits": 0
}
```
